import React, { useState } from 'react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose }) => {
  const [selectedFormat, setSelectedFormat] = useState<'pdf' | 'idf' | 'trnsys' | 'csv'>('pdf');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleDownload = () => {
    let content = '';
    let filename = '';
    let type = 'text/plain';

    if (selectedFormat === 'pdf') {
      window.print();
      return;
    } else if (selectedFormat === 'idf') {
      filename = 'SIH26051_Leh_Passive_Shelter_v3.4.idf';
      content = `!- EnergyPlus Input Data File (IDF)
!- Model: Himalayan Passive Solar Shelter (Leh, 3524m ASL)
!- Generated by ShelterTherm v3.4 Engineering Console
Version, 23.2;
SimulationControl, Yes, Yes, Yes, Yes, Yes;
Building, Himalayan_Passive_Shelter_v3_4, 0.0, Suburbs, 0.04, 0.4, FullExterior, 25;
Site:Location, LEH_AIRPORT_LADAKH_IND, 34.1526, 77.5771, 5.5, 3524.0;
Material, Rockwool_R50, VeryRough, 0.28, 0.034, 120, 840;
Material, Rammed_Earth_Trombe, MediumRough, 0.38, 0.95, 2050, 1260;
WindowMaterial:Glazing, Triple_Argon_LowE, SpectralAverage, 0.006, 0.73, 0.08, 0.08, 0.04, 0.84, 0.05, 0.9, 0.9;
Construction, Exterior_Roof_Assembly, Rockwool_R50;
Construction, Trombe_Thermal_Wall, Rammed_Earth_Trombe;
Zone, Main_Living_Habitat, 0, 0, 0, 0, 1, 1, 174.0;
`;
    } else if (selectedFormat === 'trnsys') {
      filename = 'SIH26051_TRNSYS_Deck.dck';
      content = `* TRNSYS Simulation Deck for Himalayan Extreme Habitat
* Sector: Leh District, UT Ladakh
* Solver: Type 56 Multi-Zone Building + Type 36 Trombe Wall
EQUATIONS 4
LAT = 34.1526
ALT = 3524
T_AMB_MIN = -24.2
SOLAR_FLUX_PEAK = 890
UNIT 15 TYPE 15 Weather Data Reader
PARAMETERS 2
1 1
UNIT 56 TYPE 56 Multi-Zone Thermal Building Model
INPUTS 6
T_AMB SOL_RAD WIND_SPD REL_HUM ROCK_BED_T TROMBE_AIR
END
`;
    } else {
      filename = 'SIH26051_7Day_Hourly_Telemetry.csv';
      content = `Timestamp,Day,Hour,T_Indoor_C,T_Ambient_C,Solar_Flux_Wm2,Heat_Loss_kWh,Autonomy_Pct
2026-01-15T00:00,Day1,0,17.2,-24.0,0,1.8,94.2
2026-01-15T06:00,Day1,6,16.5,-22.5,15,2.1,94.2
2026-01-15T12:00,Day1,12,19.8,-10.5,850,0.4,94.2
2026-01-15T13:00,Day1,13,20.8,-9.4,890,0.2,94.2
2026-01-15T18:00,Day1,18,19.1,-16.8,80,1.2,94.2
2026-01-18T13:00,Day4,13,20.8,-9.4,890,0.1,95.1
`;
      type = 'text/csv';
    }

    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const copyDossierText = () => {
    const text = `SHELTERTHERM • SIH26051 TECHNICAL DOSSIER SUMMARY
Project: Himalayan Passive Shelter
Location: Leh District, UT Ladakh (3,524m ASL)
Design: Iteration v3.4 [Passive Solar + Trombe Wall]
Envelope R-Value: R-48.5 hr·ft²·°F/Btu
Trombe Thermal Lag: 8.4 Hours Release
Indoor Operative Range: 16.5°C – 21.2°C (Mean 18.4°C)
Outdoor Ambient Min: -24.2°C
Thermal Autonomy: 94.2% Zero-Auxiliary Fuel Consumption
Standard: Compliant with ASHRAE 55-2023 & IS:3792 Zone V`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-xs p-4 select-none">
      <div className="bg-white rounded border border-slate-300 w-full max-w-xl shadow-xl flex flex-col overflow-hidden">
        {/* Header */}
        <div className="bg-primary-container px-4 py-3 flex items-center justify-between text-white border-b border-slate-700">
          <div className="flex items-center gap-2">
            <span className="material-symbols-outlined text-secondary text-[20px]">description</span>
            <div className="flex flex-col">
              <span className="font-headline-sm text-sm font-semibold leading-tight">
                Export Technical Engineering Deliverables
              </span>
              <span className="font-meta-caps text-[9px] text-slate-400">
                SIH26051 High-Altitude Passive Habitat Certification
              </span>
            </div>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-white transition-colors">
            <span className="material-symbols-outlined text-[20px]">close</span>
          </button>
        </div>

        {/* Content */}
        <div className="p-4 flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <label className="text-xs font-semibold text-slate-700 uppercase font-meta-caps">
              Select Deliverable Package
            </label>
            <div className="grid grid-cols-2 gap-2">
              <button
                onClick={() => setSelectedFormat('pdf')}
                className={`p-3 rounded text-left border transition-all flex flex-col ${
                  selectedFormat === 'pdf'
                    ? 'border-secondary bg-orange-50 text-slate-900 shadow-xs'
                    : 'border-slate-200 bg-slate-50 hover:bg-slate-100 text-slate-700'
                }`}
              >
                <div className="flex items-center justify-between font-semibold text-xs">
                  <span>SIH Technical Dossier</span>
                  <span className="material-symbols-outlined text-[16px] text-secondary">picture_as_pdf</span>
                </div>
                <span className="text-[10px] text-slate-500 mt-1">
                  Full 14-page PDF documentation with engineering schematics & compliance proof.
                </span>
              </button>

              <button
                onClick={() => setSelectedFormat('idf')}
                className={`p-3 rounded text-left border transition-all flex flex-col ${
                  selectedFormat === 'idf'
                    ? 'border-secondary bg-orange-50 text-slate-900 shadow-xs'
                    : 'border-slate-200 bg-slate-50 hover:bg-slate-100 text-slate-700'
                }`}
              >
                <div className="flex items-center justify-between font-semibold text-xs">
                  <span>EnergyPlus IDF Model</span>
                  <span className="material-symbols-outlined text-[16px] text-secondary">terminal</span>
                </div>
                <span className="text-[10px] text-slate-500 mt-1">
                  Building geometry, Trombe zones, construction assemblies for standard BEM solvers.
                </span>
              </button>

              <button
                onClick={() => setSelectedFormat('trnsys')}
                className={`p-3 rounded text-left border transition-all flex flex-col ${
                  selectedFormat === 'trnsys'
                    ? 'border-secondary bg-orange-50 text-slate-900 shadow-xs'
                    : 'border-slate-200 bg-slate-50 hover:bg-slate-100 text-slate-700'
                }`}
              >
                <div className="flex items-center justify-between font-semibold text-xs">
                  <span>TRNSYS Deck (.dck)</span>
                  <span className="material-symbols-outlined text-[16px] text-secondary">schema</span>
                </div>
                <span className="text-[10px] text-slate-500 mt-1">
                  Validated multi-zone Type 56 deck for transient alpine verification.
                </span>
              </button>

              <button
                onClick={() => setSelectedFormat('csv')}
                className={`p-3 rounded text-left border transition-all flex flex-col ${
                  selectedFormat === 'csv'
                    ? 'border-secondary bg-orange-50 text-slate-900 shadow-xs'
                    : 'border-slate-200 bg-slate-50 hover:bg-slate-100 text-slate-700'
                }`}
              >
                <div className="flex items-center justify-between font-semibold text-xs">
                  <span>Hourly CSV Telemetry</span>
                  <span className="material-symbols-outlined text-[16px] text-secondary">table_chart</span>
                </div>
                <span className="text-[10px] text-slate-500 mt-1">
                  Raw 168-hour simulation time-series, solar insolation, and flux balances.
                </span>
              </button>
            </div>
          </div>

          {/* Dossier Preview Summary */}
          <div className="bg-slate-100 p-3 rounded text-xs border border-slate-200 flex flex-col gap-1 font-mono">
            <div className="flex items-center justify-between text-[11px] font-bold text-slate-800">
              <span>PROJECT: SIH26051-LEH-V3.4</span>
              <button
                onClick={copyDossierText}
                className="text-[10px] text-secondary hover:underline flex items-center gap-1 font-sans"
              >
                <span className="material-symbols-outlined text-[14px]">
                  {copied ? 'check' : 'content_copy'}
                </span>
                <span>{copied ? 'Copied' : 'Copy Summary'}</span>
              </button>
            </div>
            <div className="text-[10px] text-slate-600 space-y-0.5 mt-1">
              <div>• Thermal Envelope: R-48.5 hr·ft²·°F/Btu (Rockwool + Aerogel + Foamglas)</div>
              <div>• Passive Solar Gain: 42.8 kWh/d | Storage Mass: 14.6 kWh</div>
              <div>• Sub-Zero Cold Snap Hold: 72h down to -24.2°C ambient</div>
              <div>• Net Autonomous Energy Balance: +4.6 kWh/day surplus</div>
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex items-center justify-end gap-2 pt-2 border-t border-slate-200">
            <button
              onClick={onClose}
              className="px-3 py-1.5 rounded border border-slate-300 text-slate-700 text-xs hover:bg-slate-100 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleDownload}
              className="px-4 py-1.5 rounded bg-primary text-white text-xs font-semibold hover:bg-slate-800 transition-colors flex items-center gap-1 shadow-sm"
            >
              <span className="material-symbols-outlined text-[16px]">
                {selectedFormat === 'pdf' ? 'print' : 'download'}
              </span>
              <span>{selectedFormat === 'pdf' ? 'Print / Export PDF' : 'Download File'}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
